- app/models/suggestion.rb
added one validation to suggestions lol
> added validations

- app/models/kid.rb
- app/models/user.rb
Added a dependent: :destroy for users on the kids model.
> added a dependency for kids and their user

- chirpy_extension/Chirpy_chrome_extension/api_statistics.rb
- chirpy_extension/Chirpy_chrome_extension/manifest.json
- chirpy_extension/Chirpy_chrome_extension/scripts/hide_tweets.js
- chirpy_extension/Chirpy_chrome_extension/scripts/popup.js
> just added files

- chirpy_extension/IBM_tone_analyzer/example_analysis.json
- chirpy_extension/IBM_tone_analyzer/fake_texts.json
- chirpy_extension/IBM_tone_analyzer/tones.rb
just want to add the play files
> just want to add the files

- app/controllers/statistics_controller.rb
- app/models/kid.rb
- app/models/statistic.rb
- app/services/IBM_tone_analyzer/tones.rb
- db/migrate/20220212083348_create_statistics.rb
- test/controllers/statistics_controller_test.rb
- test/models/statistic_test.rb
added stats to DB and made a controller we shall see if its needed. made an example method but havent tested it of course and its mostly theoretical atm
> added a stats table to db

- app/services/IBM_tone_analyzer/tones.rb
- app/services/example_analysis.json
- app/services/test.rb
just saving progress - doesn't impact much of anything, but the code is still pretty theoretical. 
It only works with the example analysis file I made but needs to be revised once we know
what kind of data we actually have
but I think it will be a useful springboard.
> Statistics create method

- app/controllers/statistics_controller.rb
- chirpy_extension/test_IBM_tone_analyzer/test_tones.rb
- db/migrate/20220214073023_add_refernce_to_statistics.rb
- db/schema.rb
just tweaked the create method a bit for stats (not that anything is working lol)
> changed up the create method slightly

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_sidebar.scss
- app/controllers/dashboards_controller.rb
- app/views/dashboards/index.html.erb
- app/views/layouts/application.html.erb
> dashboard css

- app/assets/stylesheets/components/_home-buttons.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
Homepage design, Im not married to the idea of any of this so it can and will change.
VH on opening page is 98 just to show that there is another page to scroll down to. Maybe 95 is better? Lemme know?
> made a super basic homepage that scrolls down.

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/policies/application_policy.rb
- app/policies/article_policy.rb
- app/policies/dashboard_policy.rb
- app/policies/kid_policy.rb
- app/policies/statistic_policy.rb
- test/policies/article_policy_test.rb
- test/policies/dashboard_policy_test.rb
- test/policies/kid_policy_test.rb
- test/policies/statistic_policy_test.rb
Pundit made. Nothing incorporated in any views. Also did not include any "authorize @something" in our controllers. So please remember to add policy when you change the controller
> Basic Pundit made

- Gemfile
- Gemfile.lock
- app/controllers/api/v1/base_controller.rb
- app/controllers/api/v1/statistics_controller.rb
- app/controllers/application_controller.rb
- app/models/user.rb
- app/policies/statistic_policy.rb
- app/views/api/v1/statistics/index.json.jbuilder
- app/views/api/v1/statistics/show.json.jbuilder
- config/routes.rb
- db/migrate/20220216150812_add_token_to_users.rb
- db/schema.rb
Added Api 
-Made Api V1 Controller
-Added Basic Controller logic for Api
-Added Pundit for Api
-Added a View.Json with Jbuilder
-Added authentication token with a gem
Maybe we could tweak things with the "Create Method" to use the "Tone analyzer" when a create POST request is made and maybe we could send back a response?
> Chirpy api

- app/controllers/kids_controller.rb
- app/views/kids/show.html.erb
- db/seeds.rb
redid the seeds to deal with validations
> fixed the seeds

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
- db/migrate/20220217132948_remove_username_from_user.rb
Added a kind of description page. I think it looks nice, what do you think?
> added a description page

- app/views/pages/home.html.erb
Found same image without istock branding
> found a better image without the istock branding

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
- app/views/shared/_footer.html.erb
Added a footer as shown, Its really basic but its a start. 
Also, cant get the icons to show up properly...
> created a footer for website. Not finished yet.

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
Added a testimonial section in, its really basic.
I have also changed the footer to just render on the home page as of now.
> added a small testimonials section

- app/assets/stylesheets/components/_footer.scss
- app/views/shared/_footer.html.erb
Little stuff for the home page
> SOme little things here and there on the home page

- app/views/pages/home.html.erb
- app/views/shared/_footer.html.erb
small typo and punctuation fixes
> fixed some typos

- app/views/articles/index.html.erb
- app/views/shared/_sidebar.html.erb
> added dashboard button

- app/views/shared/_footer.html.erb
Just removed the FA buttons that wern't showing down the bottom
> removed the shit fucking FA icons for the moment

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_sidebar.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_kids.scss
- app/controllers/kids_controller.rb
- app/views/dashboards/index.html.erb
- app/views/kids/show.html.erb
- config/routes.rb
I adjusted the design for the dashboard and made some fixes on the kids show page. 
I tried to add a delete word button but I need help with both the function and the positioning (so there for now, but not a final version)
> adjust design based upon feedback

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/components/_sidebar.scss
- app/assets/stylesheets/pages/_dashboard.scss
- app/javascript/toggle_active.js
- app/views/articles/index.html.erb
- app/views/articles/show.html.erb
- app/views/dashboards/index.html.erb
- app/views/shared/_navbar.html.erb
- app/views/shared/_sidebar.html.erb
Well, I added some CSS and adjusted things so that when the screen is small/mobile the sidebar will switch to a small navbar. I used the lewagon template but its not playing well with me. Plan to get help on tuesday with MANY styling issues. 
I also started the logic for toggling the active class on the dashboard items but someone who knows JS can finish that up if they would like to.
> Add sidenav

- app/javascript/packs/application.js
- app/javascript/plugins/calc_age.js
- app/views/kids/_form.html.erb
- app/views/kids/_new.html.erb
Added placeholder for 
-ethnicity
-sexual orientation
-gender
-Names
Added Javascript to calculate the "Age" from the "Date of Birth" and input it into the Age input which is now HIDDEN. This auto-updates on an input event listener.
Floated submit btn right and cancel left. Change cancel button to "danger-outline"
> Adding placehold kids

- app/views/articles/show.html.erb
> styled a little of the show page

- Gemfile
- Gemfile.lock
- app/controllers/api/v1/statistics_controller.rb
- app/controllers/application_controller.rb
- chirpy_extension/Chirpy_chrome_extension/manifest.json
- chirpy_extension/Chirpy_chrome_extension/popup.html
- chirpy_extension/Chirpy_chrome_extension/scripts/get_tweets.js
- chirpy_extension/Chirpy_chrome_extension/scripts/popup.js
- config/initializers/cors.rb
now just need to add some if/else to the create method
> getting correct tweet info with fetch method

- app/controllers/api/v1/statistics_controller.rb
Made the method to determine if the tweet is nasty or not. 
Thanks Gary :)
> made the bad_tweet method

- app/assets/stylesheets/components/_footer.scss
- app/controllers/api/testtweet.rb
- app/controllers/api/v1/statistics_controller.rb
- app/views/shared/_footer.html.erb
Added what we went over so far.
Also added in the footer icons again, obviously no FA icon is actually showing though...
> Footer icons

- app/models/article.rb
- db/seeds.rb
added 10 seeds, not impressive I know but I twied
> FINALLY finished seeds

- app/assets/stylesheets/config/_fonts.scss
- app/assets/stylesheets/pages/_articles.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/articles/show.html.erb
> Article show articles font

- app/views/articles/show.html.erb
- app/views/pages/_support_form.html.erb
- app/views/pages/support.html.erb
- app/views/shared/_sidebar.html.erb
- config/routes.rb
> Basic Support page

- app/views/shared/_sidebar.html.erb
Changed to link_to  helpers as the sign out had a bug before.
Changed the "Chirpy" into a link to go to the home page.
Added active class to the support page
> changed links in sidebar to link_to helpers

- app/controllers/api/v1/statistics_controller.rb
- chirpy_extension/Chirpy_chrome_extension/scripts/get_tweets.js
- debugged bad_tweet method
- get_tweet if statement to hide tweet and add class "checked"
- get tweet if statement to not run if the tweet has "checked" class
> Extension debug

- app/assets/stylesheets/components/_form.scss
- app/javascript/components/init_toggle_search.js
- app/javascript/packs/application.js
- app/views/articles/index.html.erb
- app/views/layouts/application.html.erb
https://user-images.githubusercontent.com/10571103/155530525-4a5405f2-0d01-4dd2-8246-8b7c5fb4493a.mov
@CamillieFu Let me know what you think about the color and style of the search button/bar.
> search bar button toggle

- app/views/pages/home.html.erb
Looks like this now, much cleaner in my opinion.
> removed the signout button on homepage, its not needed.

- app/controllers/api/v1/statistics_controller.rb
- app/controllers/statistics_controller.rb
added stats method and seeds, yeah thats about it
> made some fake stats and the stats method

- app/assets/stylesheets/components/_button.scss
- app/views/pages/home.html.erb
Changed the colour of the download button to have a gradient of the pink we have been using.
Text hover goes black, which I think looks ok.
> changed the colour of the download button so it pops more.

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/_card.scss
- app/javascript/packs/application.js
- app/views/kids/show.html.erb
- db/seeds.rb
- package.json
- yarn.lock
Made the kids dashboard stat
s
> manually added some files

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/config/_colors.scss
- app/views/articles/_list.html.erb
- app/views/articles/index.html.erb
changed card styling and added a pink hover effect to h3
> updated styling of articles index page

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_button.scss
- app/views/dashboards/index.html.erb
- app/views/kids/show.html.erb
- db/seeds.rb
> did a few things

- app/views/articles/index.html.erb
> added a small padding bottom to the search bar

- app/controllers/users_controller.rb
- app/views/devise/registrations/new.html.erb
-fixed the first_name and last_name is the params for making a user
> fix for registration params

- db/seeds.rb
> adjusted the seeds so that there is a range of dates

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_card.scss
- app/controllers/dashboards_controller.rb
- app/javascript/packs/application.js
- app/views/dashboards/index.html.erb
- app/views/layouts/application.html.erb
I would like to update the code so that a random selection of articles is chosen each time.
Not married to the styling (or lack thereof) either, so can be changed
> added a suggested articles section

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/shared/_footer.html.erb
Added a small banner animation going through the gradient, its a step for making the homepage look cooler?
> Banner animation

- app/views/shared/_footer.html.erb
added a single ! in the footer
> added an ! mark

- app/controllers/application_controller.rb
- app/controllers/users_controller.rb
Fix for sign up. Needed configure permitted params in the application controller for devise
> permiet first and last name at registration

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
Should be uniform with the other parts that are below. Changed the class of the p above the button and added a new photo too.
> made the front page better? Added more headings and also a new image.

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/config/_fonts.scss
- app/assets/stylesheets/pages/_articles.scss
- app/views/pages/home.html.erb
-also made a small padding change to the search bar
> added serif font for article text

- app/assets/stylesheets/components/_sidebar.scss
Aligned the Chirpy on the sidebar to be on the same level as the kid card and profile card.
> changed 8rem to 7rem

- app/assets/stylesheets/components/_footer.scss
> added a tiny bit of BR to the font awesome boxes

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_sidebar.scss
- app/views/articles/index.html.erb
- app/views/dashboards/index.html.erb
- app/views/pages/support.html.erb
> adjusted margins

- app/views/pages/support.html.erb
Changed the images and names on support so they don't clash with the testimonials
> Changed support to different people

- app/assets/stylesheets/components/_card.scss
- app/views/dashboards/_kids.html.erb
added a transition for the kid card with image
> added hover transition to kid photo

- app/assets/stylesheets/components/_card.scss
- app/views/articles/show.html.erb
- db/seeds.rb
added qanon article.
you can reseed everything or just comment out everything and add only the article.
conversely, you can just add the article through your rails c if you dont want to reseed.
> Qanon article

- app/controllers/api/v1/statistics_controller.rb
will remove all punctuation from the string we send to the IBM API
> added a regex gsub

- chirpy_extension/Chirpy_chrome_extension/popup.html
- chirpy_extension/Chirpy_chrome_extension/scripts/popup.js
- chirpy_extension/Chirpy_chrome_extension/style/popup.css
> Extension style

- app/javascript/components/home.js
- app/javascript/controllers/index.js
- app/javascript/packs/application.js
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- package.json
- yarn.lock
Added some typed.js to the homepage banner, we might not want to actually use it so I've kept it commented out for the moment. 
But it;s in there just in case?
> Typed js homepage

- Gemfile.lock
- app/assets/stylesheets/components/_card.scss
- app/views/articles/_list.html.erb
- app/views/articles/show.html.erb
- app/views/dashboards/_articles.html.erb
- db/seeds.rb
I added simple format to the articles
> added simple_format

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_form.scss
- app/views/articles/index.html.erb
- app/views/articles/show.html.erb
> Article fixes

- app/assets/stylesheets/components/_card.scss
- app/views/dashboards/_articles.html.erb
fixed the suggested articles issue
> fixed sizing issue

- app/assets/stylesheets/components/_button.scss
- app/javascript/components/home.js
- app/views/pages/home.html.erb
> changed the duration of the face from 1500 to 2500

- Gemfile.lock
- app/assets/stylesheets/components/_testimonials.scss
- app/views/pages/home.html.erb
changed the padding a little bit on the top bot and sides
Lemme know what you think.
> changed the padding of the twitter testimonials

- app/assets/stylesheets/components/_footer.scss
- app/javascript/components/home.js
- app/views/shared/_footer.html.erb
Sped up the fade speed for the animations
Also added a small copyright section down bottom
> AOS and copyright

- chirpy_extension/Chirpy_chrome_extension/popup.html
> change parent to guardian

- app/controllers/kids_controller.rb
- now if the "add word" button is pressed with nothing typed, a flash message will pop up
- 
https://user-images.githubusercontent.com/10571103/156970416-b865298f-b61c-45a5-83ad-0a2c788b4ed8.mov
> added another condition to the add word to dictionary method

- app/controllers/api/v1/statistics_controller.rb
- app/models/statistic.rb
- app/views/kids/show.html.erb
might need to make some stats before we can see the results but tentatively this is what I got so far
> made a tentative way to add blocked words to pie chart

- app/controllers/kids_controller.rb
> bandaid fix

- app/views/pages/home.html.erb
- app/views/pages/support.html.erb
Changed both the support and the testimonial pages
Support
Testimonial
> swapped the support and the testimonials.

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
Changed a line in the testimonial. Nothing important at all..
> changed the last testimonial

- app/views/kids/show.html.erb
- db/seeds.rb
- added a minimum/maximum value for the line charts stats so the chart won't show a big jump while we practice with the extension
- line chart points connect in a straight line now. They were slightly curved before.
- added a label "scanned tweets" to line chart points
> added smarter seeds for better looking charts

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/pages/_kids.scss
- app/views/kids/show.html.erb
- made the border box around the blocked word slimmer
- made the "x" delete word button more circular
- aligned the "add word form/button" with the "Update person's details button"
- deleted a duplicate remove word class in the button.scss
> changed the style of the words in the blocked words list

- app/views/kids/show.html.erb
ordered the colors in the right order as well
> added an order to the stats

- chirpy_extension/Chirpy_chrome_extension/popup.html
changed name in extension to Caroline
> changed Camille to Caroline

- app/views/kids/show.html.erb
> donuts made

- app/views/articles/show.html.erb
> removed styling

- app/assets/stylesheets/components/_testimonials.scss
- app/views/pages/home.html.erb
Updated these but you guys still might want to check them out.,
Here is 2 different resolutions that I tested.
Big
Smaller
> all testimonial cards should now be the same size.

- app/views/kids/show.html.erb
> updated donuts

- app/views/dashboards/_profile_card.html.erb
- app/views/kids/show.html.erb
> chnaged button from blue to secondary(grey)

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_kids.scss
- app/views/kids/show.html.erb
> removed a css element that was fucking with the button

- app/assets/stylesheets/components/_card.scss
- app/views/dashboards/_articles.html.erb
- app/views/dashboards/index.html.erb
- Added a pink hover effect
- Added a small border radius to the suggested articles box to blend more with the feel of the page
- Added more words to the suggested articles (truncate 90)
> Suggested article hover effect

- app/assets/stylesheets/components/_card.scss
- app/views/dashboards/_articles.html.erb
- app/views/dashboards/index.html.erb
Reverts CamillieFu/chirpy#187
reverted
> Revert "Suggested article hover effect"

- app/views/pages/home.html.erb
- app/views/pages/support.html.erb
> fixed some wording stuff

- chirpy_extension/Chirpy_chrome_extension/manifest.json
take tabs off permission on manifest
> take tabs off permission

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_sidebar.scss
- app/views/dashboards/index.html.erb
adjusted suggested article for mobile
> adjusted suggested articles

- app/views/shared/_navbar.html.erb
fixed the signout for the navbar (missing the method: :delete)
> fixed the sign out button in the navbar

- app/views/pages/home.html.erb
Made the home page HTML easier to read and more spaced out.
> HTML formatting

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/pages/_home.scss
Added the banner to its own component to get rid of the clutter on the _home.scss
> Banner component created and filled

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/components/_sidebar.scss
- app/assets/stylesheets/components/_testimonials.scss
- app/assets/stylesheets/pages/_kids.scss
just cleaned out useless comments and properties/values
> cleaned more of the scss pages and components

- chirpy_extension/Chirpy_chrome_extension/popup.html
- chirpy_extension/Chirpy_chrome_extension/scripts/popup.js
- chirpy_extension/Chirpy_chrome_extension/style/popup.css
Added child login to extension
https://user-images.githubusercontent.com/84076465/159516324-6ac2dcee-9f7e-4a15-9e20-ff6e9db06584.mov
> Child login

- README.md
These can be changed to anything we want, all found on shields.io
> added some badges to the readme file.

- app/assets/stylesheets/components/_button.scss
> changed box shadow a tiny bit

- app/views/articles/show.html.erb
> added navbar for article show page
